# Generated by Django 3.1.7 on 2021-09-18 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='公告', max_length=200)),
                ('content', models.CharField(default='公告内容', max_length=1000)),
                ('releases_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-releases_time'],
            },
        ),
        migrations.CreateModel(
            name='OjInfo',
            fields=[
                ('name', models.CharField(default='OJ', max_length=30, primary_key=True, serialize=False)),
                ('pages', models.IntegerField(default=0)),
                ('problems_count', models.IntegerField(default=0)),
                ('url', models.CharField(default='#', max_length=1000)),
                ('has_problem_spider', models.BooleanField(default=False)),
                ('last_problem_spider_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_contest_spider', models.BooleanField(default=False)),
                ('last_contest_spider_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
